version: "3"

services:
  flask:
    image: datafabric_flask
    build: ./web/flask
    depends_on:
      - redis
      - mysql
      - mongo
      - recommender
      - rabbitmq
    networks:
      datafabric_network:
    ports:
      - 5000:5000
    volumes:
      - ./web/flask/flask-share:/flask-share
      - ./web/flask/datafabric.py:/datafabric.py
      - ./web/flask/flask_config.json:/flask_config.json
      - ./web/flask/static:/static
      - ./web/flask/template:/template
      - ./web/flask/InternalDB:/InternalDB
      - ./web/flask/InternalMQ:/InternalMQ
      - ./web/flask/DBMSAccessor:/DBMSAccessor
      - ./web/flask/DatafabricManager:/DatafabricManager
      - ./web/flask/RecommenderService:/RecommenderService
      - ./web/flask/DataIntegrationService:/DataIntegrationService
      - ./web/flask/DatafabricTools:/DatafabricTools
      - ./test:/test
    mem_limit: 4096MB
  
  redis:
    image: redis:7.0.0
    networks:
      datafabric_network:
    mem_limit: 4096MB
    volumes:
      - ./persistent_storage/redis:/data

  mysql:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      datafabric_network:
    volumes:
      - ./persistent_storage/mysql/mysql-data:/var/lib/mysql
      - ./conf/mysql/conf:/etc/mysql/conf.d
    mem_limit: 4096MB

  mongo:
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      datafabric_network:
    volumes:
      - ./persistent_storage/mongo/mongo-data:/data/db
      - ./persistent_storage/mongo/conf:/data/configdb
    mem_limit: 4096MB

  recommender:
    image: datafabric_recommender
    build: ./recommender
    depends_on:
      - mongo
    user: root
    environment:
      GRANT_SUDO: "yes"
    volumes:
      - ./recommender/recommender_microservice.py:/home/jovyan/recommender_microservice.py
      - ./recommender/jupyter_work:/home/jovyan/work
    networks:
      datafabric_network:
    mem_limit: 4096MB

  rabbitmq:
    image: rabbitmq:3.9.10-management
    networks:
      datafabric_network:
    volumes:
      - ./conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./persistent_storage/rabbitmq:/var/lib/rabbitmq
    mem_limit: 1024MB

  data-integration:
    image: datafabric_data-integration
    deploy:
      replicas: 3
    build: ./data_integration
    depends_on:
      - rabbitmq
    volumes:
      - ./data_integration/microservice.py:/microservice.py
      - ./data_integration/task_requests:/task_requests
      - ./data_integration/task_logs:/task_logs
      - ./data_integration/integration_results:/integration_results
      - ./data_integration/data_serving:/data_serving
      - ./data_integration/DataIntegrator:/DataIntegrator
      - ./data_integration/DBMSAccessor:/DBMSAccessor
    networks:
      datafabric_network:
    mem_limit: 4096MB

networks:
  datafabric_network:
    external:
      name: datafabric_network