version: "2"

services:
  flask:
    image: datafabric-flask
    build: ./web/flask
    container_name: datafabric-flask
    hostname: datafabric-flask
    depends_on:
      - redis
      - mysql
      - mongo
      - recommender
      - rabbitmq
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.2
    env_file:
      - ./web/flask/flask.env
    ports:
      - 5000:5000
    volumes:
      - ./web/flask/flask-share:/flask-share
      - ./web/flask/datafabric.py:/datafabric.py
      - ./web/flask/datafabric.log:/datafabric.log
      - ./web/flask/flask_config.json:/flask_config.json
      - ./web/flask/static:/static
      - ./web/flask/template:/template
      - ./common/InternalDB:/InternalDB
      - ./common/InternalMQ:/InternalMQ
      - ./common/DBMSAccessor:/DBMSAccessor
      - ./web/flask/DatafabricManager:/DatafabricManager
      - ./web/flask/RecommenderService:/RecommenderService
      - ./test:/test
    mem_limit: 4096MB
  
  redis:
    image: redis:7.0.0
    container_name: datafabric-redis
    hostname: datafabric-redis
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.3
    mem_limit: 4096MB
    volumes:
      - ./persistent_storage/redis:/data

  mysql:
    image: mysql:8.0.29
    container_name: datafabric-mysql
    hostname: datafabric-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.4
    volumes:
      - ./persistent_storage/mysql/mysql-data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    mem_limit: 4096MB

  mongo:
    image: mongo:5.0.8
    container_name: datafabric-mongo
    hostname: datafabric-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.5
    volumes:
      - ./persistent_storage/mongo/mongo-data:/data/db
      - ./persistent_storage/mongo/conf:/data/configdb
    mem_limit: 4096MB

  recommender:
    image: datafabric-recommender
    build: ./recommender
    container_name: datafabric-recommender
    hostname: datafabric-recommender
    depends_on:
      - mongo
    user: root
    environment:
      GRANT_SUDO: "yes"
    volumes:
      - ./recommender/recommender_microservice.py:/home/jovyan/recommender_microservice.py
      - ./recommender/recommender_microservice.log:/home/jovyan/recommender_microservice.log
      - ./recommender/jupyter_work:/home/jovyan/work
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.6
    mem_limit: 4096MB

  rabbitmq:
    image: rabbitmq:3.9.10-management
    container_name: datafabric-rabbitmq
    hostname: datafabric-rabbitmq
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.7
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./persistent_storage/rabbitmq:/var/lib/rabbitmq
    mem_limit: 1024MB

  data-integration:
    image: datafabric-data-integration
    build: ./data_integration
    container_name: datafabric-data-integration
    hostname: datafabric-data-integration
    depends_on:
      - rabbitmq
    volumes:
      - ./data_integration/microservice.py:/microservice.py
      - ./data_integration/microservice.log:/microservice.log
    networks:
      datafabric_network:
        ipv4_address: 172.22.0.8
    mem_limit: 4096MB

networks:
  datafabric_network:
    external:
      name: datafabric_network