version: "3"

services:
  flask:
    image: datafabric_flask
    deploy:
      replicas: 3
    environment:
      - N_WORKERS=16
      - MYSQL_HOST=192.168.103.56
      - MYSQL_PORT=3306
      - MONGODB_HOST=192.168.103.56
      - MONGODB_PORT=27017
      - REDIS_HOST=192.168.103.56
      - REDIS_PORT=6379
      - RABBITMQ_HOST=192.168.103.56
      - RABBITMQ_PORT=5672
    build: ./web/flask
    depends_on:
      - redis
      - mysql
      - mongo
      - recommender
      - rabbitmq
    networks:
      datafabric_network:
    volumes:
      - ./web/flask/flask-share:/flask-share
      - ./web/flask/datafabric.py:/datafabric.py
      - ./web/flask/flask_config.json:/flask_config.json
      - ./web/flask/static:/static
      - ./web/flask/template:/template
      - ./web/flask/InternalDB:/InternalDB
      - ./web/flask/InternalMQ:/InternalMQ
      - ./web/flask/DBMSAccessor:/DBMSAccessor
      - ./web/flask/DatafabricManager:/DatafabricManager
      - ./web/flask/RecommenderService:/RecommenderService
      - ./web/flask/DataIntegrationService:/DataIntegrationService
      - ./web/flask/DatafabricTools:/DatafabricTools
      - ./test:/test
    mem_limit: 8192MB
    ports:
        5000:5000

  recommender:
    image: datafabric_recommender
    build: ./recommender
    depends_on:
      - mongo
    user: root
    environment:
      - GRANT_SUDO=yes
      - MYSQL_HOST=192.168.103.56
      - MYSQL_PORT=3306
      - MONGODB_HOST=192.168.103.56
      - MONGODB_PORT=27017
      - REDIS_HOST=192.168.103.56
      - REDIS_PORT=6379
      - RABBITMQ_HOST=192.168.103.56
      - RABBITMQ_PORT=5672
    volumes:
      - ./recommender/recommender_microservice.py:/home/jovyan/recommender_microservice.py
      - ./recommender/jupyter_work:/home/jovyan/work
    networks:
      datafabric_network:
    mem_limit: 4096MB

  data-integration:
    image: datafabric_data-integration
    deploy:
      replicas: 3
    build: ./data_integration
    depends_on:
      - rabbitmq
    environment:
      - MYSQL_HOST=192.168.103.56
      - MYSQL_PORT=3306
      - MONGODB_HOST=192.168.103.56
      - MONGODB_PORT=27017
      - REDIS_HOST=192.168.103.56
      - REDIS_PORT=6379
      - RABBITMQ_HOST=192.168.103.56
      - RABBITMQ_PORT=5672
    volumes:
      - ./data_integration/microservice.py:/microservice.py
      - ./data_integration/task_requests:/task_requests
      - ./data_integration/task_logs:/task_logs
      - ./data_integration/integration_results:/integration_results
      - ./data_integration/data_serving:/data_serving
      - ./data_integration/DataIntegrator:/DataIntegrator
      - ./data_integration/DBMSAccessor:/DBMSAccessor
      - ./data_integration/InternalMQ:/InternalMQ
    networks:
      datafabric_network:
    mem_limit: 4096MB

networks:
  datafabric_network:
    external:
      name: datafabric_network
