version: "3"

services:
  nginx:
    image: nginx:1.23.0
    depends_on:
      - flask
    networks:
      datafabric_network:
    ports:
      - 5000:80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    mem_limit: 8192MB
  
  redis:
    image: redis:7.0.0
    networks:
      datafabric_network:
    mem_limit: 4096MB
    volumes:
      - ./persistent_storage/redis:/data
    ports:
        6379:6379

  mysql:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      datafabric_network:
    volumes:
      - ./persistent_storage/mysql/mysql-data:/var/lib/mysql
      - ./conf/mysql/conf:/etc/mysql/conf.d
    mem_limit: 4096MB
    ports:
        3306:3306

  mongo:
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      datafabric_network:
    volumes:
      - ./persistent_storage/mongo/mongo-data:/data/db
      - ./persistent_storage/mongo/conf:/data/configdb
    mem_limit: 4096MB
    ports:
        27017:27017

  rabbitmq:
    image: rabbitmq:3.9.10-management
    networks:
      datafabric_network:
    volumes:
      - ./conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./persistent_storage/rabbitmq:/var/lib/rabbitmq
    mem_limit: 1024MB
    ports:
      - 15672:15672
      - 5672:5672

networks:
  datafabric_network:
    external:
      name: datafabric_network
